### ISSUE TITLE
Packaged Chromium cannot log into account

### ISSUE THREAD

**Issue by vbc4ejyg** [igor-starostenko/book-worm#2]
Hello,

I cannot get past the auto script that should log in using the package chromium.  I am trying to import 1200 saved places on google maps.

>  MINGW64 ~/Downloads/Git/book-worm (master)
$ node src/run.js --unhandled-rejections=strict
(node:6456) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector "header[role="banner"]" failed: timeout 30000ms exceeded
    at new WaitTask (C:\Users\and\Downloads\Git\node_modules\puppeteer\lib\DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (C:\Users\and\Downloads\Git\node_modules\puppeteer\lib\DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (C:\Users\and\Downloads\Git\node_modules\puppeteer\lib\DOMWorld.js:432:17)
    at Frame.waitForSelector (C:\Users\and\Downloads\Git\node_modules\puppeteer\lib\FrameManager.js:627:47)
    at Frame.<anonymous> (C:\Users\and\Downloads\Git\node_modules\puppeteer\lib\helper.js:112:23)
    at Frame.waitFor (C:\Users\and\Downloads\Git\node_modules\puppeteer\lib\FrameManager.js:612:19)
    at Page.waitFor (C:\Users\and\Downloads\Git\node_modules\puppeteer\lib\Page.js:1113:29)
    at C:\Users\and\Downloads\Git\book-worm\src\run.js:33:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled p
romise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Chromium shows:

> This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

However if I launch chromium by itself I can log into the account just fine.

**Comment by igor-starostenko** [comment]
Google could have changed the UI since I wrote the script. I’ll probably need to update the selectors

**Comment by igor-starostenko** [comment]
@madfusker I'm on macOS and I don't get the error. I also tried running the script on Windows 10 VM and I get through login. Have you tried refreshing the screen as the error says? May be it's antivirus blocking it?
Also I would try upgrading puppeteer to the latest:
```
npm uninstall puppeteer
npm install puppeteer
```

**Comment by igor-starostenko** [comment]
@madfusker I finally managed to reproduce the error. Apparently Google no longer allows to use automation frameworks with their products. https://support.google.com/accounts/answer/7675428
We'll need to find a workaround

**Comment by vbc4ejyg** [comment]
Thanks for taking a look!
